ARG TUMBLEWEED=opensuse/tumbleweed@sha256:0aecc6219df43c7c21f752f68a08ec26b9f65473e100f6e82fa28a773d4925de
FROM ${TUMBLEWEED}
RUN zypper addlock glibc # https://github.com/moby/moby/issues/42680
RUN zypper install -y container-selinux git rpm-build selinux-policy-devel

ENV DAPPER_SOURCE /source
ENV DAPPER_OUTPUT ./dist
ENV DAPPER_ENV COMBARCH DRONE_TAG TAG
ENV HOME ${DAPPER_SOURCE}
WORKDIR ${DAPPER_SOURCE}

ENTRYPOINT ["./policy/microos/scripts/entry"]
